name: Publish Package

on:
  push:
    tags: [v*]

permissions:
  contents: read

concurrency:
  group: npm-publish
  cancel-in-progress: false

jobs:
  publish-npm:
    runs-on: ubuntu-24.04
    environment: Publish Package
    permissions:
      contents: write
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v7
        with:
          fetch-depth: 0

      - name: Setup pnpm
        uses: pnpm/setup@v3
        with:
          install: false

      - name: Setup Node.js
        uses: actions/setup-node@v7
        with:
          node-version: 24
          package-manager-cache: false

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Setup npm with Trusted Publishing support
        run: npm install --global npm@12.2.0

      - name: Publish to npm with OIDC
        run: pnpm publish:ci

      - name: Create GitHub Release
        run: pnpm dlx changelogithub --no-group
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
